### ISSUE TITLE
time algo not working in Safari mode

### ISSUE THREAD

**Issue by kakshay21** [gokulkrishh/anonymous-web#4]
even after 10 min the log still says just now

**Comment by gokulkrishh** [comment]
@kakshay21 Probably issue with `timeago.js` library which I am using. Thanks for reporting.

**Comment by kakshay21** [comment]
very clean UI by the way! I love it!!
I want to build something similar with vue js. My app is already pwa ready and it's configured with firebase. would you help me in UI?

**Comment by gokulkrishh** [comment]
@kakshay21 Hey, Thanks. You can take the components and related CSS in the repo. Try running it locally to get a local demo of it.

**Comment by kakshay21** [comment]
Yeah, I did on my local as the link isn't working now. Thanks! 
Would you mind if I contact you, when I fall in any problem with codes?

**Comment by kakshay21** [comment]
Okay I take that as no.
The code is very modular and well placed. Are components standalone? Will it work with just template? Just to clarify, I want to use the html/css in my existing Vuejs project.
@gokulkrishh

**Comment by gokulkrishh** [comment]
@kakshay21 No code is not modular. I have written some  specific codes.  Check out the code you will know more.
